### ISSUE TITLE
How to locate the code section on Addon?

### ISSUE THREAD

**Issue by imakou** [Pickra/copy-code-block#10]
Hi,

This add-on is really helpful for me for HTML displaying.
But, just want to know if there is any way to put "copy section" on add-on rather than the main section?

Thanks.

![image](https://user-images.githubusercontent.com/1507950/52918108-4806e880-32c1-11e9-96a6-07bac52ea903.png)

**Comment by Pickra** [comment]
Hey @imakou, glad this is helping you. Unfortunately, it won't do what you're asking for.
It's not a Storybook Addon exactly, meaning it's not integrated with storybook. It's just a function, that returns your code in a format that can be copied and used in Storybook or wherever.

I haven't looked into integrating it with Storybook's ecosystem, but I imagine you'll run into some of [the same issues](https://github.com/storybooks/storybook/issues/4832) which caused me to build `copy-code-block` in the first place.

You might be able to turn off the addon panel with the [addons-options showAddonPanel](https://github.com/storybooks/storybook/tree/master/addons/options) and [add a decorator globally for all stories](https://storybook.js.org/addons/introduction/) and move `copy-code-block` to a permanent "section" for all stories, but again, I haven't looked into it.

Good luck
