### ISSUE TITLE
aria-labelledby attribute mispelled on container element

### ISSUE THREAD

**Issue by maxleaver** [Pickra/copy-code-block#11]
The aria-labelledby attribute on line 28 of copyCodeBlock.js is mispelled, causing it to not function correctly. The correct spelling has two L's. I'll submit a PR with a quick fix.

**Line with Typo:**
https://github.com/Pickra/copy-code-block/blob/f6a046b2fbbe2d82f1aa26d0c51c0cdf28b84539/src/copyCodeBlock.js#L28

**Comment by Pickra** [comment]
Appreciate the assist
